#!/usr/bin/env bash
if [ -z $1 -a -z $2 ]
then
	echo "bin me usage: binme [name of the file to be bin'd] [bin'd file name]"
	exit 1
else
	ls $(pwd)/$1 2>/dev/null && sudo ln -s $(pwd)/$1 /usr/bin/$2 2>/dev/null || ls $1 2>/dev/null && sudo ln -s $1 /usr/bin/$2 2>/dev/null || echo "an error has ocurred"
	echo "binme: symlink /usr/bin/$2 created successfully"
fi
