#!/usr/bin/sh
# esse script tem esse nome pela facilidade de digitar e apenas isso.

# se nenhuma variavel global estiver definada para DIO_FOLDER, definir uma:
[ -z $DIO_FOLDER ] && DIO_FOLDER=$HOME/dio


dio_help(){ 
	printf "a função principal de dio pode ser acessada com um (e apenas um) simples \"dio\" na linha de comando.\nqualquer coisa inserida após \"dio\" será interpretada como um argumento. segue abaixo uma meia lista das opções de comandos aceitados por dio no momento:\n"
	printf "help\nadd\nlist\nremove\n\n"
		exit
} 


add_dio(){

	[ -z $1 ] && dio_help || ORIGIN=$1
	[ -z $2 ] && TARGET=$(basename $1) || TARGET=$2

	if [ -e $ORIGIN ]
	then
		ln -s $(realpath $ORIGIN) $DIO_FOLDER/$TARGET 1>/dev/null \
		&& echo "dio: link simbólico de $ORIGIN criado em $DIO_FOLDER/"
	else 
		printf "dio: arquivo $ORIGIN inexistente? por favor verifique se o nome do arquivo foi digitado corretamente.\n\n"
	fi 
}


dio_choose(){ 
	ESCOLHA=$(realpath $DIO_FOLDER/$(ls $DIO_FOLDER | dmenu)) 


	if [ -e $ESCOLHA ]
	then 
		if [ -w $ESCOLHA ]
		then 
			edit $ESCOLHA
			exit
		else
			printf "permissões inssuficientes para editar aquivo. indo sudo.\n" \
			&& sudoedit $ESCOLHA 
		fi
	fi
}


case $1 in 
	add)
		add_dio $2 $3
		;;
	list)
		ls -1 $DIO_FOLDER 
		;;
	remove)
		rm -i $DIO_FOLDER/$2
		;;
	help)
		dio_help
		;;
	h)
		dio_help
		;;
	-help)
		dio_help
		;;
	--help)
		dio_help
		;;
	*) 
		dio_choose
		;;
esac
