#!/usr/bin/sh
# se chama dio pq é fácil digitar dio. mais nada.


# dio pode usar uma variável global como local da pasta caso uma esteja definida
if [ -z $DIO_FOLDER ]; then
	DIO_FOLDER=$HOME/dio
elif ! [ -d $DIO_FOLDER ]; then
	printf "dio: variável externa DIO_FOLDER encontrada no entanto nenhuma pasta " 
	printf "correspondente foi localizada. criando uma.\n" && mkdir $DIO_FOLDER \
	&& exit \
	|| printf "dio: falha ao criar pasta. algum erro ocorreu" \
	&& exit
fi 

dio_help(){ 
	printf "dio: a função principal de dio pode ser acessada com um (e apenas um) simples \"dio\" na linha de comando.\nqualquer coisa inserida após \"dio\" será interpretada como um argumento. segue abaixo uma meia lista das opções de comandos aceitadas por dio no momento:\n"
	printf "help\nadd\nlist\nremove\n\n"
		exit
} 
add_dio(){

	[ -z $1 ] && dio_help || ORIGIN=$1
	[ -z $2 ] && TARGET=$(basename $1) || TARGET=$2

	if [ -e $ORIGIN ]
	then
		ln -s $(realpath $ORIGIN) $DIO_FOLDER/$TARGET 1>/dev/null \
		&& echo "dio: link simbólico de $ORIGIN criado em $DIO_FOLDER/"
	else 
		printf "dio: arquivo $ORIGIN inexistente? por favor verifique se o nome do arquivo foi digitado corretamente.\n\n"
	fi 
} 
dio_choose(){ 
	ESCOLHA=$(realpath $DIO_FOLDER/$(ls $DIO_FOLDER | dmenu)) 


	if [ -e $ESCOLHA ] && ! [ $ESCOLHA = $DIO_FOLDER ]
	#dmenu retorna o stdin prévio caso nehum texto seja inserido (ex. pressionando "esc")  
	then 
		if [ -w $ESCOLHA ]; then 
			edit $ESCOLHA
			exit
		else
			printf "permissões insuficientes para editar arquivo. indo sudo.\n" \
			&& sudoedit $ESCOLHA 
		fi
	fi
} 

#main
case $1 in 
	add)
		add_dio $2 $3
		;;
	list)
		echo "links presentes em $DIO_FOLDER:"
		ls -1 $DIO_FOLDER 
		;;
	remove)
		[ -z $2 ] && printf "dio: por favor insira o nome do link a ser apagado\n\"dio list\" para exibir todos os links presentes em $DIO_FOLDER\n" \
		|| rm -i $DIO_FOLDER/$2
		;;
	help)
		dio_help
		;;
	h)
		dio_help
		;;
	-help)
		dio_help
		;;
	--help)
		dio_help
		;;
	*) 
		dio_choose
		;;
esac
