#!/usr/bin/env bash

exec 3>/dev/null

MNT=$HOME/mount

if [[ $(ls -A $HOME/mount) ]]; then
	sudo umount $MNT 2>&3 && echo "mm: volume unmounted" || echo "mm: something went wrong whilst attemping to unmount volume. perhaps volume is busy at the moment?" >&2 
	exit 1
else
	echo "mm: no volumes detected. mount a new volume:"
	sudo mount /dev/$1 $MNT 2>&3 || sudo mount /dev/$(ls /dev | grep sd | dmenu) $MNT 2>&3 || echo "no volumes selected or selected volume was invalid" >&2
fi
